version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/phpunit-bridge
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/messenger
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.1
  - dependency-name: symfony/process
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/yaml
    versions:
    - 5.2.1
    - 5.2.3
  - dependency-name: friendsofsymfony/rest-bundle
    versions:
    - 3.0.4
  - dependency-name: phpro/grumphp
    versions:
    - 1.3.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pdfmake
    versions:
    - 0.1.70
  - dependency-name: datatables.net-dt
    versions:
    - 1.10.23
  - dependency-name: datatables.net-bs
    versions:
    - 1.10.23
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: jszip
    versions:
    - 3.5.0
