dh_doctrine_audit:
    # Configuration reference available at:
    # https://github.com/DamienHarper/DoctrineAuditBundle#configuration
    entities:
        App\Entity\User:
            ignored_columns:
                - lastLogin
                - updatedAt
        App\Entity\Test: ~ # all properties are audited