fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: '%user_class%'
    group:
        group_class: '%group_class%'
    from_email:
        address: '%env(resolve:MAILER_FROM_ADDRESS)%'
        sender_name: '%env(resolve:MAILER_FROM_NAME)%'
    service:
        mailer: fos_user.mailer.twig_swift
    change_password:
        form:
            type:               App\Form\User\ChangePasswordType
            validation_groups:  [ChangePassword, Default]
    profile:
        form:
            type:               App\Form\User\ProfileUserType
            validation_groups:  [Profile, Default]
    registration:
        confirmation:
            enabled: true
            template: 'email/account/register/email.html.twig'
            from_email:
                address: '%env(resolve:MAILER_FROM_ADDRESS)%'
                sender_name: '%env(resolve:MAILER_FROM_NAME)%'
        form:
            type: App\Form\User\RegisterUserType
            validation_groups:  [Registration, Default]
    resetting:
        email:
            template: 'email/account/resetting/email.html.twig'
        form:
            type: App\Form\User\ResettingPasswordType
            validation_groups:  [ResetPassword, Default]