twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        available_colors: '%available_colors%'
        available_locales: '%available_locales%'
        cookie_policy_url: '%cookie_policy_url%'
        logo: '%logo%'
        recaptcha_apikey: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        skeleton_version: '%skeleton_version%'
