twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        available_locales: '%available_locales%'
        available_colors: '%available_colors%'
        skeleton_version: '%skeleton_version%'
