twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        available_colors: '%available_colors%'
        available_locales: '%available_locales%'
        cookie_policy_url: '%cookie_policy_url%'
        current_domain: '%env(resolve:CURRENT_DOMAIN)%'
        http_protocol: '%env(resolve:HTTP_PROTOCOL)%'
        logo: '%logo%'
        publish_url: '%env(resolve:MERCURE_PUBLISH_URL)%'
        recaptcha_apikey: '%env(resolve:GOOGLE_RECAPTCHA_SITE_KEY)%'
