services:
    App\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\EventListener\NotificationListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.success, method: onRegistrationSuccess }
            - { name: kernel.event_listener, event: event.user.added, method: onUserAdded }

    App\EventListener\MaintenanceListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: event.maintenance.viewed, method: onMaintenanceViewed }

    App\EventListener\UserListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: fos_user.registration.success, method: onRegistrationSuccess }
            - { name: kernel.event_listener, event: event.user.edited, method: onUserEdited }
