# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    skeleton_version: 1.0.1
    locale: 'fr'
    available_locales: fr|en|de
    available_functionalities:
        - func.switch_theme
        - func.switch_locale
        - func.clear_cache
        - func.audit
        - func.confirm_delete
        - func.form_watcher
        - func.manage_settings
    available_colors:
        - red
        - pink
        - purple
        - deep-purple
        - indigo
        - blue
        - light-blue
        - cyan
        - teal
        - green
        - light-green
        - lime
        - yellow
        - amber
        - orange
        - deep-orange
        - brown
        - grey
        - blue-grey
        - black
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $locale: '%locale%'
            $recaptacha_secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'
            $available_locales: '%available_locales%'
            $available_colors: '%available_colors%'
            $available_functionalities: '%available_functionalities%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Factory,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Maker\MakeSkeleton:
        arguments:
            - '@maker.doctrine_helper'
            - '@maker.renderer.form_type_renderer'
        tags: ['maker.command']

    App\Menu\Builder\NavbarBuilder:
        arguments: ['@knp_menu.factory']
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: navbar }

    App\Menu\Builder\TopbarBuilder:
        arguments: ['@knp_menu.factory']
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: topbar }

    App\Menu\Builder\UserDropdownBuilder:
        arguments: ['@knp_menu.factory']
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: usernav }

    App\Menu\Renderer\TopbarRenderer:
        arguments:
            - '@knp_menu.matcher'
        tags:
            - { name: knp_menu.renderer, alias: topbar_renderer }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
